### ISSUE TITLE
Parse errors on strings containing a single quote

### ISSUE THREAD

**Issue by bobziuchkovski** [fktn-k/fkYAML#217]
### Description

When parsing a scalar value that contains a `'`  character within it, fkYAML throws an exception.

### Reproduction steps

Try parsing either of the following:

```yaml
stuff:
  - id: foo
    name: "Bob's stuff"
```

```yaml
stuff:
  - id: foo
    name: Bob's stuff
```

Both should be valid YAML, but the single quote throws off the parser: `fkyaml::v0_2_1::exception: Invalid single quotation mark found in a string token.`

### Expected vs. actual results

Expected: Parse the name field as "Bob's stuff" string.
Actual: Exception thrown: `fkyaml::v0_2_1::exception: Invalid single quotation mark found in a string token.`

### Compiler and operating system

Clang on MacOS 13.6

### Library version

develop HEAD

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/fktn-k/fkYAML/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/fktn-k/fkYAML#how-to-execute-the-unit-tests).

**Comment by fktn-k** [comment]
@bobziuchkovski   
Thanks for your report!  
I misunderstood the specification for single quotation marks (like they must be escaped, which is not true as you pointed out).  
This IS a bug and I'll fix it soon.

**Comment by bobziuchkovski** [comment]
No problem. And honestly there's no hurry on my end. I'm able to work-around it just fine.

**Comment by fktn-k** [comment]
@bobziuchkovski   
Thanks, but I've already made local changes to fkYAML with which can successfully parse strings containing single quotes.  
I'll create a PR for the changes tonight.

**Comment by fktn-k** [comment]
@bobziuchkovski   
The PR fixing this issue has been merged!  
Since all the CI checks have passed, the fix should be fine on your environment.

**Comment by bobziuchkovski** [comment]
Confirmed! This is working as expected now. Thanks!

**Comment by fktn-k** [comment]
@bobziuchkovski   
Thanks! I'll close this issue then:)
