### ISSUE TITLE
Output stream conversion of nodes lacks quoting/escape of string values

### ISSUE THREAD

**Issue by bobziuchkovski** [fktn-k/fkYAML#218]
### Description

While testing fkYAML, I noticed the output stream conversion of fkyaml::node string values lack quoting, which can change the YAML doc's semantics.

Example: a string value of "1" should be output with quoting or else it becomes an integral value in the output, which changes the semantics.

### Reproduction steps

Parse and then output the following YAML doc:

Input doc:
```yaml
stuff:
  - id: '1'
    name: Foo
```
fkYAML output representation (string scalar value becomes an integer)
```yaml
stuff:
  -
    id: 1
    name: Foo
```

### Expected vs. actual results

Expected: output representation retains semantic equality of input doc.
Actual: output representation changes semantic equality of input doc.

### Minimal code example

```c++
std::ifstream ifs("test.yaml");
fkyaml::node root = fkyaml::node::deserialize(ifs);
std::cout << root << std::endl;
```

### Compiler and operating system

Clang on MacOS 13.6

### Library version

develop HEAD

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/fktn-k/fkYAML/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/fktn-k/fkYAML#how-to-execute-the-unit-tests).

**Comment by fktn-k** [comment]
@bobziuchkovski   
Thanks for sharing the issue.  
I just realized the serialization feature does nothing to avoid such cases (currently it just works like a simple extension of the std::to_string function).  
It must have some functionalities to preserve semantic equality between an input and an output.

**Comment by fktn-k** [comment]
@bobziuchkovski   
Trying to fix the issues reported here on [this branch](https://github.com/fktn-k/fkYAML/tree/bugfix/218_fix_lacking_quotes_escapes_on_output).  
I guess most of the related issues have already been resolved.

**Comment by fktn-k** [comment]
@bobziuchkovski   
The PR which fixes the issue related to missing quotes/escapes in serialized string values, has been merged.  
I think the reported issues have been fixed on the HEAD of the develop branch.

**Comment by fktn-k** [comment]
@bobziuchkovski   
Thanks! It's good to hear that:D  
I'll close this issue then.
