### ISSUE TITLE
Embedded flow indicators in plain unquoted scalar values cause incorrect parse results

### ISSUE THREAD

**Issue by stephenwhittle** [fktn-k/fkYAML#292]
### Description

This issue is similar to #275 , but concerns values rather than keys. 
A flow sequence or mapping indicator is currently treated by the parser as the end of a plain unquoted scalar value, even outside of a flow collection.

### Reproduction steps

The following minimal YAML demonstrates the issue:
```yaml
KEY:
          description: Cryptographic key, bits [159 :128]
```

### Expected vs. actual results

The entire string `Cryptographic key, bits [159 :128]` should be treated as the value, but because the lexer treats [ as the end of a string, the resulting tree contains a key of 159 and a value of 128 with the rest of the string being discarded.

In my testing, checking `m_flow_context_depth` before treating those indicators as string terminators in the lexer, seems to address this issue.

### Compiler and operating system

VS 2022 (both clang-cl and msvc compilers), Win 10

### Library version

04e1a7b9115398ae8c57c0f5263dcb8390e3dc32

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/fktn-k/fkYAML/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/fktn-k/fkYAML#how-to-execute-the-unit-tests).

**Comment by fktn-k** [comment]
@stephenwhittle   
Thanks for the bug report!  
I overlooked that part while fixing the issue you referred in the description.  

Also, I totally agree with your solution and thanks again for the PR.  
I'll take a look soon.
